version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123@Mudar"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  projeto-exemplo:
    build: .
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "80:8080"